apiVersion: v1
kind: Pod
metadata:
  name: hello-skaffold
  labels:
    app: hello-skaffold
spec:
  containers:
  - name: hello-skaffold
    image: hello-skaffold-image
  - name: nginx
    image: nginx
    ports:
      - name: nginx
        containerPort: 80


